### ISSUE TITLE
Dahua not loaded after update in Home Assistant core 2024.11.0b0

### ISSUE THREAD

**Issue by jodomi** [rroller/dahua#406]
After update core 2024.10.4 to 2024.11.0b0 Dahua not loaded with 2 devices: 
Generic RTSP by Dahua Firmware: 1.0
 and 
DHI-VTO2211G-WP by Dahua Firmware: 4.511.0000000.0.R,build:2021-11-16.
Try to reboot, delete and re-install same error.

**Comment by dvbit** [comment]
Reporting the same issue. Tried to delete ad add again the camera but got . 
Impossibile caricare il flusso di configurazione: {"message":"Invalid handler specified"}

**Comment by Pastaloverzzz** [comment]
Here to report the same issue, this is what my logs say:

Seems like he's stuck on:     from homeassistant.core import Config, HomeAssistant, callback
ImportError: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'? (bottom)

Logger: homeassistant.setup
Bron: setup.py:334
Eerst voorgekomen: 00:23:46 (1 gebeurtenissen)
Laatst gelogd: 00:23:46

Setup failed for custom integration 'recycle_app': Unable to import component: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1011, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/recycle_app/__init__.py", line 9, in <module>
    from homeassistant.core import Config, HomeAssistant, callback
ImportError: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1071, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/recycle_app/__init__.py", line 9, in <module>
    from homeassistant.core import Config, HomeAssistant, callback
ImportError: cannot import name 'Config' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py). Did you mean: 'config'?

**Comment by rroller** [comment]
Thanks. I'm out of town and only have my work laptop. I'll try to get this fixed once I get back tomorrow or the next.

**Comment by Pastaloverzzz** [comment]
These are the fixes from another integration (RecycleApp) that had the same error, hope this helps you.

You can find the changes on that app here or the picture below: https://github.com/olibos/HomeAssistant-RecycleApp/compare/v2.5.2...v2.5.3-b1

![afbeelding](https://github.com/user-attachments/assets/28594410-9074-4bc9-a6d9-00092fe2f6a0)

**Comment by Pastaloverzzz** [comment]
> It's working!, Thanks

How did you get it to work? I tried changing the _init_ file with the above lines but it didn't work. (Not a programmer but like to figure this out since it seems simple :) )

**Comment by jodomi** [comment]
What i've done:
Edit /homeassistant/custom_components/dahua/__init__.py, replace ** ** with "" "", add ++ ++


"""
Custom integration to integrate Dahua cameras with Home Assistant.
"""
import asyncio
from typing import Any, Dict
import logging
import ssl
import time

from datetime import timedelta

from homeassistant.components.tag import async_scan_tag
import hashlib

from aiohttp import ClientError, ClientResponseError, ClientSession, TCPConnector
from homeassistant.config_entries import ConfigEntry
**from homeassistant.core import CALLBACK_TYPE, Config, HomeAssistant`_**
""from homeassistant.core import CALLBACK_TYPE, HomeAssistant""
from homeassistant.exceptions import ConfigEntryNotReady, PlatformNotReady
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.typing import ConfigType
++from homeassistant.helpers.typing import ConfigType++
from homeassistant.const import EVENT_HOMEASSISTANT_STOP

from custom_components.dahua.thread import DahuaEventThread, DahuaVtoEventThread
from . import dahua_utils
from .client import DahuaClient

from .const import (
    CONF_EVENTS,
    CONF_PASSWORD,
    CONF_PORT,
    CONF_USERNAME,
    CONF_ADDRESS,
    CONF_NAME,
    DOMAIN,
    PLATFORMS,
    CONF_RTSP_PORT,
    STARTUP_MESSAGE,
    CONF_CHANNEL,
)
from .dahua_utils import parse_event
from .vto import DahuaVTOClient

SCAN_INTERVAL_SECONDS = timedelta(seconds=30)

SSL_CONTEXT = ssl.create_default_context()
SSL_CONTEXT.set_ciphers("DEFAULT")
SSL_CONTEXT.check_hostname = False
SSL_CONTEXT.verify_mode = ssl.CERT_NONE

_LOGGER: logging.Logger = logging.getLogger(__package__)


**async def async_setup(hass: HomeAssistant, config: Config):**
""async def async_setup(hass: HomeAssistant, config: ConfigType):""
    """
    Set up this integration with the UI. YAML is not supported.
    https://developers.home-assistant.io/docs/asyncio_working_with_async/
    """
    hass.data.setdefault(DOMAIN, {})
    return True


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry):
async def async_setup_entry(hass: HomeAssistant, entry: ConfigType):    
    """Set up this integration using UI."""

**Comment by Pastaloverzzz** [comment]
Jep, that did it, was the same as i tried the first time but i must have messed something up 👍

**Comment by Pastaloverzzz** [comment]
@jodomi I made a pull request, but are you sure the last ConfigEntry has to change to ConfigType on the lines beneath?

** async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry): **
"" async def async_setup_entry(hass: HomeAssistant, entry: ConfigType): ""

It seems to be working with both, but i think it has to stay the same since ConfigEntry is also imported here:
from homeassistant.config_entries import ConfigEntry

**Comment by jodomi** [comment]
I have no idea about that, i'm not  dev just an adept of Ctrl+c Ctrl+v ;-)

**Comment by Pastaloverzzz** [comment]
Haha, same here. Will leave ConfigEntry like it is. 

@rroller pull request is submitted :)
Hope i did it the right way, it's my first pull request so if you have any remarks please let me know :)

![afbeelding](https://github.com/user-attachments/assets/c48c3aa5-8e96-4e9f-ac0a-b81fff38b992)

**Comment by rroller** [comment]
I merged and did the release for https://github.com/rroller/dahua/pull/408

Can you try it out? I had to do this from my mobile phone so I'm unable to test it.

**Comment by dvbit** [comment]
@rroller works. Thank you. BTW you have a pull request for some Italian translations. Cheers

**Comment by rroller** [comment]
@dvbit thanks. The Italian translations were already merged. Thanks again!
